# Generated by Django 5.2.1 on 2025-10-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapped',
            name='shorter_url',
            field=models.CharField(max_length=20),
        ),
    ]
